import Rupert.Affine
import Rupert.Attr
import Rupert.Basic
import Rupert.Convex
import Rupert.Cube
import Rupert.FinCases
import Rupert.Icosahedron
import Rupert.MatrixSimps
import Rupert.Quaternion
import Rupert.Equivalences.RupertEquivRupertPrime
import Rupert.Equivalences.RupertEquivRupertSet
import Rupert.Equivalences.AffineRupertEquivRupertSet
import Rupert.Set
import Rupert.SnubCube
import Rupert.Square
import Rupert.Tetrahedron
import Rupert.TriakisTetrahedron
